projects:
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
  - name: crossplane
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Crossplane
    sourceRepos:
    - '*'
    destinations:
    - namespace: crossplane
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
applications:
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
        - values.yaml
        - ../values-argocd.yaml
      path: argocd/argocd-install/argo-cd
      repoURL: https://github.com/flerwin/infra.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
        - values.yaml
        - ../values-argocd-apps.yaml
      path: argocd/argocd-install/argocd-apps
      repoURL: https://github.com/flerwin/infra.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
  - name: applications
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd/applications
      repoURL: https://github.com/flerwin/infra.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
  - name: application-projects
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd/application-projects
      repoURL: https://github.com/flerwin/infra.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
  - name: crossplane
    namespace: argocd
    destination:
      namespace: crossplane
      server: https://kubernetes.default.svc
    project: crossplane
    source:
      helm:
        version: v3
        valueFiles:
        - values.yaml
      path: crossplane/crossplane
      repoURL: https://github.com/flerwin/infra.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
